package com.app.dc.service.simulation.runtime;

public class StrategyBacktestSummary {
    public String sid;
    public String strategyName;
    public String strategyVersion;
    public String symbolScope;
    public String runtimeType;
    public String executionModelVersion;
    public String scene;
    public String runTime;
    public String windowMode;
    public Integer sliceCount;
    public String optimizationMode;
    public Integer trialCount;
    public Integer bestRank;
    public String bestParamSetJson;
    public Double fitPnl;
    public Double validatePnl;
    public Double forwardPnl;
    public Double totalPnl;
    public Double forwardScore;
    public Double validatePrimaryScore;
    public Double forwardAuxScore;
    public Double feeAdjustedValidatePnl;
    public Double feeAdjustedForwardPnl;
    public Double sliceParamDriftScore;
    public Integer oosPass;
    public Integer validateTradeCount;
    public Double validateMaxDrawdownPct;
    public Double validateProfitFactor;
    public Integer fragileBest;
    public Double minForwardContribution;
    public Integer overfitPass;
    public String overfitReason;
    public Integer resultCount;
    public Boolean sceneQualificationPass;
    public String sceneQualificationReason;
    public Integer sceneRecordCount;
    public Integer sceneMatchedBarCount;
    public Integer sceneTradeCount;
    public Double scenePnl;
    public Double sceneProfitFactor;
    public Double sceneMaxDrawdownPct;
    public Boolean fullPeriodSafetyPass;
    public String fullPeriodSafetyReason;
}
