serverKey=SERVER.SIMSvr

apsServerKey=SERVER.APSSvr
quantServerKey=SERVER.QuantSvr
textList=15m|30m|1h|4h|1d
symbolList=ETHUSDT|BTCUSDT|SOLUSDT
queryKlineCount=200
queryKlineCount1d=400

log4j.file=./config/log4j.ini
log4j.thread=1
log4j.writeTime=true
log4j.async=true

storePath=./data/SIMSvr

dbpool.cfg=./config/DBPoolConfig.ini
dbType=rockdb
#clickhouse.default=ClickHouse1
